#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BattleRoadStartEffect_LevelInstance_31

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BattleRoadStartEffect_LevelInstance_31.BattleRoadStartEffect_C
// 0x0000 (0x0228 - 0x0228)
class ABattleRoadStartEffect_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BattleRoadStartEffect_C">();
	}
	static class ABattleRoadStartEffect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABattleRoadStartEffect_C>();
	}
};
static_assert(alignof(ABattleRoadStartEffect_C) == 0x000008, "Wrong alignment on ABattleRoadStartEffect_C");
static_assert(sizeof(ABattleRoadStartEffect_C) == 0x000228, "Wrong size on ABattleRoadStartEffect_C");

}

