#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BattleSystem_LevelInstance_30

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BattleSystem_LevelInstance_30.BattleSystem_C
// 0x0000 (0x0268 - 0x0268)
class ABattleSystem_C final : public ANicolaBattleLevel
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BattleSystem_C">();
	}
	static class ABattleSystem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABattleSystem_C>();
	}
};
static_assert(alignof(ABattleSystem_C) == 0x000008, "Wrong alignment on ABattleSystem_C");
static_assert(sizeof(ABattleSystem_C) == 0x000268, "Wrong size on ABattleSystem_C");

}

