#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BL_BT_Romaria_BattleRoad_LevelInstance_32

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BL_BT_Romaria_BattleRoad_LevelInstance_32.BL_BT_Romaria_BattleRoad_C
// 0x0000 (0x0268 - 0x0268)
class ABL_BT_Romaria_BattleRoad_C final : public ANicolaBattleLevel
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BL_BT_Romaria_BattleRoad_C">();
	}
	static class ABL_BT_Romaria_BattleRoad_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABL_BT_Romaria_BattleRoad_C>();
	}
};
static_assert(alignof(ABL_BT_Romaria_BattleRoad_C) == 0x000008, "Wrong alignment on ABL_BT_Romaria_BattleRoad_C");
static_assert(sizeof(ABL_BT_Romaria_BattleRoad_C) == 0x000268, "Wrong size on ABL_BT_Romaria_BattleRoad_C");

}

