#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BattleSceneCapture2D

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BattleSceneCapture2D.BP_BattleSceneCapture2D_C
// 0x0000 (0x0238 - 0x0238)
class ABP_BattleSceneCapture2D_C final : public ABattleSceneCapture2D
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BattleSceneCapture2D_C">();
	}
	static class ABP_BattleSceneCapture2D_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BattleSceneCapture2D_C>();
	}
};
static_assert(alignof(ABP_BattleSceneCapture2D_C) == 0x000008, "Wrong alignment on ABP_BattleSceneCapture2D_C");
static_assert(sizeof(ABP_BattleSceneCapture2D_C) == 0x000238, "Wrong size on ABP_BattleSceneCapture2D_C");

}

