#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BattlePawn

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BattlePawn.BP_BattlePawn_C
// 0x0000 (0x02A8 - 0x02A8)
class ABP_BattlePawn_C final : public ADefaultPawn
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BattlePawn_C">();
	}
	static class ABP_BattlePawn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BattlePawn_C>();
	}
};
static_assert(alignof(ABP_BattlePawn_C) == 0x000008, "Wrong alignment on ABP_BattlePawn_C");
static_assert(sizeof(ABP_BattlePawn_C) == 0x0002A8, "Wrong size on ABP_BattlePawn_C");

}

