#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BattleLocationControl

#include "Basic.hpp"

#include "BP_BattleLocationControl_classes.hpp"
#include "BP_BattleLocationControl_parameters.hpp"


namespace SDK
{

// Function BP_BattleLocationControl.BP_BattleLocationControl_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BattleLocationControl_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BattleLocationControl_C", "ReceiveTick");

	Params::BP_BattleLocationControl_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BattleLocationControl.BP_BattleLocationControl_C.ExecuteUbergraph_BP_BattleLocationControl
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BattleLocationControl_C::ExecuteUbergraph_BP_BattleLocationControl(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BattleLocationControl_C", "ExecuteUbergraph_BP_BattleLocationControl");

	Params::BP_BattleLocationControl_C_ExecuteUbergraph_BP_BattleLocationControl Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

