#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BattlePositionLine

#include "Basic.hpp"

#include "BP_BattlePositionLine_classes.hpp"
#include "BP_BattlePositionLine_parameters.hpp"


namespace SDK
{

// Function BP_BattlePositionLine.BP_BattlePositionLine_C.P¢¯¿üK‰-š’Y‹
// (BlueprintCallable, BlueprintEvent)

void ABP_BattlePositionLine_C::P____K______Y_()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BattlePositionLine_C", "P¢¯¿üK‰-š’Y‹");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BattlePositionLine.BP_BattlePositionLine_C.ExecuteUbergraph_BP_BattlePositionLine
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BattlePositionLine_C::ExecuteUbergraph_BP_BattlePositionLine(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BattlePositionLine_C", "ExecuteUbergraph_BP_BattlePositionLine");

	Params::BP_BattlePositionLine_C_ExecuteUbergraph_BP_BattlePositionLine Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

