#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FieldTopCameraActor

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FieldTopCameraActor.BP_FieldTopCameraActor_C
// 0x0000 (0x0AC0 - 0x0AC0)
class ABP_FieldTopCameraActor_C final : public ANicolaFieldCameraActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FieldTopCameraActor_C">();
	}
	static class ABP_FieldTopCameraActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FieldTopCameraActor_C>();
	}
};
static_assert(alignof(ABP_FieldTopCameraActor_C) == 0x000010, "Wrong alignment on ABP_FieldTopCameraActor_C");
static_assert(sizeof(ABP_FieldTopCameraActor_C) == 0x000AC0, "Wrong size on ABP_FieldTopCameraActor_C");

}

