#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FieldTopPawn

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FieldTopPawn.BP_FieldTopPawn_C
// 0x0000 (0x0630 - 0x0630)
class ABP_FieldTopPawn_C final : public AFieldPlayerActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FieldTopPawn_C">();
	}
	static class ABP_FieldTopPawn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FieldTopPawn_C>();
	}
};
static_assert(alignof(ABP_FieldTopPawn_C) == 0x000010, "Wrong alignment on ABP_FieldTopPawn_C");
static_assert(sizeof(ABP_FieldTopPawn_C) == 0x000630, "Wrong size on ABP_FieldTopPawn_C");

}

