#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FieldTopPlayerController

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FieldTopPlayerController.BP_FieldTopPlayerController_C
// 0x0000 (0x05D0 - 0x05D0)
class ABP_FieldTopPlayerController_C final : public ANicolaFieldPlayerController
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FieldTopPlayerController_C">();
	}
	static class ABP_FieldTopPlayerController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FieldTopPlayerController_C>();
	}
};
static_assert(alignof(ABP_FieldTopPlayerController_C) == 0x000008, "Wrong alignment on ABP_FieldTopPlayerController_C");
static_assert(sizeof(ABP_FieldTopPlayerController_C) == 0x0005D0, "Wrong size on ABP_FieldTopPlayerController_C");

}

