#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LandingAttributeVolumeForFieldSymbol_Box

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LandingAttributeVolumeForFieldSymbol_Box.BP_LandingAttributeVolumeForFieldSymbol_Box_C
// 0x0000 (0x0268 - 0x0268)
class ABP_LandingAttributeVolumeForFieldSymbol_Box_C final : public ALandingAttributeVolumeForFieldSymbolBox
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_LandingAttributeVolumeForFieldSymbol_Box_C">();
	}
	static class ABP_LandingAttributeVolumeForFieldSymbol_Box_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LandingAttributeVolumeForFieldSymbol_Box_C>();
	}
};
static_assert(alignof(ABP_LandingAttributeVolumeForFieldSymbol_Box_C) == 0x000008, "Wrong alignment on ABP_LandingAttributeVolumeForFieldSymbol_Box_C");
static_assert(sizeof(ABP_LandingAttributeVolumeForFieldSymbol_Box_C) == 0x000268, "Wrong size on ABP_LandingAttributeVolumeForFieldSymbol_Box_C");

}

