#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LanternPointLight

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LanternPointLight.BP_LanternPointLight_C
// 0x0000 (0x0238 - 0x0238)
class ABP_LanternPointLight_C final : public APointLight
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_LanternPointLight_C">();
	}
	static class ABP_LanternPointLight_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LanternPointLight_C>();
	}
};
static_assert(alignof(ABP_LanternPointLight_C) == 0x000008, "Wrong alignment on ABP_LanternPointLight_C");
static_assert(sizeof(ABP_LanternPointLight_C) == 0x000238, "Wrong size on ABP_LanternPointLight_C");

}

