#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MN_012_SpikedhareEX

#include "Basic.hpp"

#include "BP_MonsterCharacterBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MN_012_SpikedhareEX.BP_MN_012_SpikedhareEX_C
// 0x0000 (0x0770 - 0x0770)
class ABP_MN_012_SpikedhareEX_C final : public ABP_MonsterCharacterBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MN_012_SpikedhareEX_C">();
	}
	static class ABP_MN_012_SpikedhareEX_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MN_012_SpikedhareEX_C>();
	}
};
static_assert(alignof(ABP_MN_012_SpikedhareEX_C) == 0x000010, "Wrong alignment on ABP_MN_012_SpikedhareEX_C");
static_assert(sizeof(ABP_MN_012_SpikedhareEX_C) == 0x000770, "Wrong size on ABP_MN_012_SpikedhareEX_C");

}

