#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NicolaGameSingleton

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NicolaGameSingleton.BP_NicolaGameSingleton_C
// 0x0000 (0x0058 - 0x0058)
class UBP_NicolaGameSingleton_C final : public UNicolaGameSingleton
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NicolaGameSingleton_C">();
	}
	static class UBP_NicolaGameSingleton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_NicolaGameSingleton_C>();
	}
};
static_assert(alignof(UBP_NicolaGameSingleton_C) == 0x000008, "Wrong alignment on UBP_NicolaGameSingleton_C");
static_assert(sizeof(UBP_NicolaGameSingleton_C) == 0x000058, "Wrong size on UBP_NicolaGameSingleton_C");

}

