#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NicolaUIManager

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NicolaUIManager.BP_NicolaUIManager_C
// 0x0000 (0x07D8 - 0x07D8)
class UBP_NicolaUIManager_C final : public UNicolaUIManager
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NicolaUIManager_C">();
	}
	static class UBP_NicolaUIManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_NicolaUIManager_C>();
	}
};
static_assert(alignof(UBP_NicolaUIManager_C) == 0x000008, "Wrong alignment on UBP_NicolaUIManager_C");
static_assert(sizeof(UBP_NicolaUIManager_C) == 0x0007D8, "Wrong size on UBP_NicolaUIManager_C");

}

