#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NicolaGameInstance

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NicolaGameInstance.BP_NicolaGameInstance_C
// 0x0000 (0x0568 - 0x0568)
class UBP_NicolaGameInstance_C final : public UNicolaGameInstance
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NicolaGameInstance_C">();
	}
	static class UBP_NicolaGameInstance_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_NicolaGameInstance_C>();
	}
};
static_assert(alignof(UBP_NicolaGameInstance_C) == 0x000008, "Wrong alignment on UBP_NicolaGameInstance_C");
static_assert(sizeof(UBP_NicolaGameInstance_C) == 0x000568, "Wrong size on UBP_NicolaGameInstance_C");

}

