#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPC_045_01_Swordsman

#include "Basic.hpp"

#include "BP_NonPlayerCharacterBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NPC_045_01_Swordsman.BP_NPC_045_01_Swordsman_C
// 0x0000 (0x0770 - 0x0770)
class ABP_NPC_045_01_Swordsman_C final : public ABP_NonPlayerCharacterBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NPC_045_01_Swordsman_C">();
	}
	static class ABP_NPC_045_01_Swordsman_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NPC_045_01_Swordsman_C>();
	}
};
static_assert(alignof(ABP_NPC_045_01_Swordsman_C) == 0x000010, "Wrong alignment on ABP_NPC_045_01_Swordsman_C");
static_assert(sizeof(ABP_NPC_045_01_Swordsman_C) == 0x000770, "Wrong size on ABP_NPC_045_01_Swordsman_C");

}

