#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PL_Chandelier_01_EF

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PL_Chandelier_01_EF.BP_PL_Chandelier_01_EF_C
// 0x0010 (0x0230 - 0x0220)
class ABP_PL_Chandelier_01_EF_C final : public AActor
{
public:
	class UNiagaraComponent*                      NS_Env_CandleFire_01;                              // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_PL_Chandelier_01;                               // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PL_Chandelier_01_EF_C">();
	}
	static class ABP_PL_Chandelier_01_EF_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PL_Chandelier_01_EF_C>();
	}
};
static_assert(alignof(ABP_PL_Chandelier_01_EF_C) == 0x000008, "Wrong alignment on ABP_PL_Chandelier_01_EF_C");
static_assert(sizeof(ABP_PL_Chandelier_01_EF_C) == 0x000230, "Wrong size on ABP_PL_Chandelier_01_EF_C");
static_assert(offsetof(ABP_PL_Chandelier_01_EF_C, NS_Env_CandleFire_01) == 0x000220, "Member 'ABP_PL_Chandelier_01_EF_C::NS_Env_CandleFire_01' has a wrong offset!");
static_assert(offsetof(ABP_PL_Chandelier_01_EF_C, SM_PL_Chandelier_01) == 0x000228, "Member 'ABP_PL_Chandelier_01_EF_C::SM_PL_Chandelier_01' has a wrong offset!");

}

