#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PSF_C05_Dharma

#include "Basic.hpp"

#include "BP_ProgressSpawnActor_ForField_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PSF_C05_Dharma.BP_PSF_C05_Dharma_C
// 0x0000 (0x02B0 - 0x02B0)
class ABP_PSF_C05_Dharma_C final : public ABP_ProgressSpawnActor_ForField_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PSF_C05_Dharma_C">();
	}
	static class ABP_PSF_C05_Dharma_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PSF_C05_Dharma_C>();
	}
};
static_assert(alignof(ABP_PSF_C05_Dharma_C) == 0x000008, "Wrong alignment on ABP_PSF_C05_Dharma_C");
static_assert(sizeof(ABP_PSF_C05_Dharma_C) == 0x0002B0, "Wrong size on ABP_PSF_C05_Dharma_C");

}

