#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ProgressSpawnActor_ForField

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ProgressSpawnActor_ForField.BP_ProgressSpawnActor_ForField_C
// 0x0000 (0x02B0 - 0x02B0)
class ABP_ProgressSpawnActor_ForField_C : public AProgressSpawnManagementActorForField
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ProgressSpawnActor_ForField_C">();
	}
	static class ABP_ProgressSpawnActor_ForField_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ProgressSpawnActor_ForField_C>();
	}
};
static_assert(alignof(ABP_ProgressSpawnActor_ForField_C) == 0x000008, "Wrong alignment on ABP_ProgressSpawnActor_ForField_C");
static_assert(sizeof(ABP_ProgressSpawnActor_ForField_C) == 0x0002B0, "Wrong size on ABP_ProgressSpawnActor_ForField_C");

}

