#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RichImageStatusEffectDecorator

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RichImageStatusEffectDecorator.BP_RichImageStatusEffectDecorator_C
// 0x0000 (0x0110 - 0x0110)
class UBP_RichImageStatusEffectDecorator_C final : public URichTextBlockMaterialDecorator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_RichImageStatusEffectDecorator_C">();
	}
	static class UBP_RichImageStatusEffectDecorator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_RichImageStatusEffectDecorator_C>();
	}
};
static_assert(alignof(UBP_RichImageStatusEffectDecorator_C) == 0x000008, "Wrong alignment on UBP_RichImageStatusEffectDecorator_C");
static_assert(sizeof(UBP_RichImageStatusEffectDecorator_C) == 0x000110, "Wrong size on UBP_RichImageStatusEffectDecorator_C");

}

