#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SearchEvent

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SearchEvent.BP_SearchEvent_C
// 0x0010 (0x0290 - 0x0280)
class ABP_SearchEvent_C : public ASearchEvent
{
public:
	class UArrowComponent*                        Arrow;                                             // 0x0280(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBillboardComponent*                    Billboard;                                         // 0x0288(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SearchEvent_C">();
	}
	static class ABP_SearchEvent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SearchEvent_C>();
	}
};
static_assert(alignof(ABP_SearchEvent_C) == 0x000008, "Wrong alignment on ABP_SearchEvent_C");
static_assert(sizeof(ABP_SearchEvent_C) == 0x000290, "Wrong size on ABP_SearchEvent_C");
static_assert(offsetof(ABP_SearchEvent_C, Arrow) == 0x000280, "Member 'ABP_SearchEvent_C::Arrow' has a wrong offset!");
static_assert(offsetof(ABP_SearchEvent_C, Billboard) == 0x000288, "Member 'ABP_SearchEvent_C::Billboard' has a wrong offset!");

}

