#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EasyParticle

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// Enum EasyParticle.EEasyParticleComponentType
// NumValues: 0x0003
enum class EEasyParticleComponentType : uint8
{
	PARTICLE                                 = 1,
	CHILD_EMITTER                            = 2,
	EEasyParticleComponentType_MAX           = 3,
};

// Enum EasyParticle.EComponentPriority
// NumValues: 0x0008
enum class EComponentPriority : uint8
{
	LEVEL_0                                  = 0,
	LEVEL_1                                  = 1,
	LEVEL_2                                  = 2,
	LEVEL_3                                  = 3,
	LEVEL_CHILD                              = 4,
	LEVEL_5                                  = 5,
	COUNT                                    = 5,
	EComponentPriority_MAX                   = 6,
};

// Enum EasyParticle.EEasyParticlepertyColor_Type
// NumValues: 0x0005
enum class EEasyParticlepertyColor_Type : uint8
{
	Color                                    = 0,
	ColorRange                               = 1,
	ColorCurve                               = 2,
	ColorCurveRange                          = 3,
	EEasyParticlepertyColor_MAX              = 4,
};

// Enum EasyParticle.EEasyParticlepertyFloat_Type
// NumValues: 0x0005
enum class EEasyParticlepertyFloat_Type : uint8
{
	Float                                    = 0,
	FloatRange                               = 1,
	FloatCurve                               = 2,
	FloatCurveRange                          = 3,
	EEasyParticlepertyFloat_MAX              = 4,
};

// Enum EasyParticle.EUIParticleCurveType
// NumValues: 0x0004
enum class EUIParticleCurveType : uint8
{
	LifetimePercent                          = 0,
	Lifetime                                 = 1,
	EmitterLifetime                          = 2,
	EUIParticleCurveType_MAX                 = 3,
};

// Enum EasyParticle.EEasyParticleDrawEffect
// NumValues: 0x000A
enum class EEasyParticleDrawEffect : uint8
{
	None                                     = 0,
	NoBlending                               = 1,
	PreMultipliedAlpha                       = 2,
	NoGamma                                  = 4,
	InvertAlpha                              = 8,
	NoPixelSnapping                          = 16,
	DisabledEffect                           = 32,
	IgnoreTextureAlpha                       = 64,
	ReverseGamma                             = 128,
	EEasyParticleDrawEffect_MAX              = 129,
};

// Enum EasyParticle.EUIParticleState
// NumValues: 0x0005
enum class EUIParticleState : uint8
{
	ACTIVE                                   = 0,
	SELF_END                                 = 1,
	SELF_CHILD_END                           = 2,
	IN_CACHE                                 = 3,
	EUIParticleState_MAX                     = 4,
};

// ScriptStruct EasyParticle.UIParticleFactorParam
// 0x001C (0x001C - 0x0000)
struct FUIParticleFactorParam final
{
public:
	float                                         Factor;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Factor2;                                           // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Factor3;                                           // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Factor4;                                           // 0x000C(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Lifetime;                                          // 0x0010(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LifetimePercent;                                   // 0x0014(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RootEmitterLifetime;                               // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FUIParticleFactorParam) == 0x000004, "Wrong alignment on FUIParticleFactorParam");
static_assert(sizeof(FUIParticleFactorParam) == 0x00001C, "Wrong size on FUIParticleFactorParam");
static_assert(offsetof(FUIParticleFactorParam, Factor) == 0x000000, "Member 'FUIParticleFactorParam::Factor' has a wrong offset!");
static_assert(offsetof(FUIParticleFactorParam, Factor2) == 0x000004, "Member 'FUIParticleFactorParam::Factor2' has a wrong offset!");
static_assert(offsetof(FUIParticleFactorParam, Factor3) == 0x000008, "Member 'FUIParticleFactorParam::Factor3' has a wrong offset!");
static_assert(offsetof(FUIParticleFactorParam, Factor4) == 0x00000C, "Member 'FUIParticleFactorParam::Factor4' has a wrong offset!");
static_assert(offsetof(FUIParticleFactorParam, Lifetime) == 0x000010, "Member 'FUIParticleFactorParam::Lifetime' has a wrong offset!");
static_assert(offsetof(FUIParticleFactorParam, LifetimePercent) == 0x000014, "Member 'FUIParticleFactorParam::LifetimePercent' has a wrong offset!");
static_assert(offsetof(FUIParticleFactorParam, RootEmitterLifetime) == 0x000018, "Member 'FUIParticleFactorParam::RootEmitterLifetime' has a wrong offset!");

// ScriptStruct EasyParticle.UIParticleRandomFactor
// 0x0004 (0x0004 - 0x0000)
struct alignas(0x04) FUIParticleRandomFactor final
{
public:
	uint8                                         Pad_0[0x4];                                        // 0x0000(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FUIParticleRandomFactor) == 0x000004, "Wrong alignment on FUIParticleRandomFactor");
static_assert(sizeof(FUIParticleRandomFactor) == 0x000004, "Wrong size on FUIParticleRandomFactor");

// ScriptStruct EasyParticle.EasyParticleComponentRuntime_Child_SubEmitter
// 0x0050 (0x0050 - 0x0000)
struct FEasyParticleComponentRuntime_Child_SubEmitter final
{
public:
	class UEasyParticleEmitterAsset*              Asset;                                             // 0x0000(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class UEasyParticleState*>             ChildArray;                                        // 0x0008(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
	class UEasyParticleComponent_Child_Runtime*   ComponentOwner;                                    // 0x0018(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FUIParticleRandomFactor                MaxParticleCountFactor;                            // 0x0020(0x0004)(Edit, EditConst, NoDestructor, NativeAccessSpecifierPublic)
	struct FUIParticleRandomFactor                SpawnRateFactor;                                   // 0x0024(0x0004)(Edit, EditConst, NoDestructor, NativeAccessSpecifierPublic)
	float                                         DelayActive;                                       // 0x0028(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Deadtime;                                          // 0x002C(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ChildLayer;                                        // 0x0030(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ActiveParentLifePercent;                           // 0x0034(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_38[0x18];                                      // 0x0038(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FEasyParticleComponentRuntime_Child_SubEmitter) == 0x000008, "Wrong alignment on FEasyParticleComponentRuntime_Child_SubEmitter");
static_assert(sizeof(FEasyParticleComponentRuntime_Child_SubEmitter) == 0x000050, "Wrong size on FEasyParticleComponentRuntime_Child_SubEmitter");
static_assert(offsetof(FEasyParticleComponentRuntime_Child_SubEmitter, Asset) == 0x000000, "Member 'FEasyParticleComponentRuntime_Child_SubEmitter::Asset' has a wrong offset!");
static_assert(offsetof(FEasyParticleComponentRuntime_Child_SubEmitter, ChildArray) == 0x000008, "Member 'FEasyParticleComponentRuntime_Child_SubEmitter::ChildArray' has a wrong offset!");
static_assert(offsetof(FEasyParticleComponentRuntime_Child_SubEmitter, ComponentOwner) == 0x000018, "Member 'FEasyParticleComponentRuntime_Child_SubEmitter::ComponentOwner' has a wrong offset!");
static_assert(offsetof(FEasyParticleComponentRuntime_Child_SubEmitter, MaxParticleCountFactor) == 0x000020, "Member 'FEasyParticleComponentRuntime_Child_SubEmitter::MaxParticleCountFactor' has a wrong offset!");
static_assert(offsetof(FEasyParticleComponentRuntime_Child_SubEmitter, SpawnRateFactor) == 0x000024, "Member 'FEasyParticleComponentRuntime_Child_SubEmitter::SpawnRateFactor' has a wrong offset!");
static_assert(offsetof(FEasyParticleComponentRuntime_Child_SubEmitter, DelayActive) == 0x000028, "Member 'FEasyParticleComponentRuntime_Child_SubEmitter::DelayActive' has a wrong offset!");
static_assert(offsetof(FEasyParticleComponentRuntime_Child_SubEmitter, Deadtime) == 0x00002C, "Member 'FEasyParticleComponentRuntime_Child_SubEmitter::Deadtime' has a wrong offset!");
static_assert(offsetof(FEasyParticleComponentRuntime_Child_SubEmitter, ChildLayer) == 0x000030, "Member 'FEasyParticleComponentRuntime_Child_SubEmitter::ChildLayer' has a wrong offset!");
static_assert(offsetof(FEasyParticleComponentRuntime_Child_SubEmitter, ActiveParentLifePercent) == 0x000034, "Member 'FEasyParticleComponentRuntime_Child_SubEmitter::ActiveParentLifePercent' has a wrong offset!");

// ScriptStruct EasyParticle.UIParticleRange_Color
// 0x0028 (0x0028 - 0x0000)
struct FUIParticleRange_Color final
{
public:
	struct FLinearColor                           Min;                                               // 0x0000(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           Max;                                               // 0x0010(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          RandomKey_R_G;                                     // 0x0020(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          RandomKey_R_B;                                     // 0x0021(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          RandomKey_R_A;                                     // 0x0022(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          RandomKey_G_B;                                     // 0x0023(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          RandomKey_G_A;                                     // 0x0024(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          RandomKey_B_A;                                     // 0x0025(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_26[0x2];                                       // 0x0026(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FUIParticleRange_Color) == 0x000004, "Wrong alignment on FUIParticleRange_Color");
static_assert(sizeof(FUIParticleRange_Color) == 0x000028, "Wrong size on FUIParticleRange_Color");
static_assert(offsetof(FUIParticleRange_Color, Min) == 0x000000, "Member 'FUIParticleRange_Color::Min' has a wrong offset!");
static_assert(offsetof(FUIParticleRange_Color, Max) == 0x000010, "Member 'FUIParticleRange_Color::Max' has a wrong offset!");
static_assert(offsetof(FUIParticleRange_Color, RandomKey_R_G) == 0x000020, "Member 'FUIParticleRange_Color::RandomKey_R_G' has a wrong offset!");
static_assert(offsetof(FUIParticleRange_Color, RandomKey_R_B) == 0x000021, "Member 'FUIParticleRange_Color::RandomKey_R_B' has a wrong offset!");
static_assert(offsetof(FUIParticleRange_Color, RandomKey_R_A) == 0x000022, "Member 'FUIParticleRange_Color::RandomKey_R_A' has a wrong offset!");
static_assert(offsetof(FUIParticleRange_Color, RandomKey_G_B) == 0x000023, "Member 'FUIParticleRange_Color::RandomKey_G_B' has a wrong offset!");
static_assert(offsetof(FUIParticleRange_Color, RandomKey_G_A) == 0x000024, "Member 'FUIParticleRange_Color::RandomKey_G_A' has a wrong offset!");
static_assert(offsetof(FUIParticleRange_Color, RandomKey_B_A) == 0x000025, "Member 'FUIParticleRange_Color::RandomKey_B_A' has a wrong offset!");

// ScriptStruct EasyParticle.EasyParticleLinearColorCurve
// 0x0208 (0x0208 - 0x0000)
struct FEasyParticleLinearColorCurve final
{
public:
	struct FRichCurve                             ColorCurves[0x4];                                  // 0x0000(0x0080)(Edit, NativeAccessSpecifierPublic)
	EUIParticleCurveType                          CurveType;                                         // 0x0200(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Loop;                                              // 0x0201(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_202[0x6];                                      // 0x0202(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FEasyParticleLinearColorCurve) == 0x000008, "Wrong alignment on FEasyParticleLinearColorCurve");
static_assert(sizeof(FEasyParticleLinearColorCurve) == 0x000208, "Wrong size on FEasyParticleLinearColorCurve");
static_assert(offsetof(FEasyParticleLinearColorCurve, ColorCurves) == 0x000000, "Member 'FEasyParticleLinearColorCurve::ColorCurves' has a wrong offset!");
static_assert(offsetof(FEasyParticleLinearColorCurve, CurveType) == 0x000200, "Member 'FEasyParticleLinearColorCurve::CurveType' has a wrong offset!");
static_assert(offsetof(FEasyParticleLinearColorCurve, Loop) == 0x000201, "Member 'FEasyParticleLinearColorCurve::Loop' has a wrong offset!");

// ScriptStruct EasyParticle.UIParticleRange_LinearColorCurve
// 0x0418 (0x0418 - 0x0000)
struct FUIParticleRange_LinearColorCurve final
{
public:
	struct FEasyParticleLinearColorCurve          Min;                                               // 0x0000(0x0208)(Edit, NativeAccessSpecifierPublic)
	struct FEasyParticleLinearColorCurve          Max;                                               // 0x0208(0x0208)(Edit, NativeAccessSpecifierPublic)
	bool                                          RandomKey_R_G;                                     // 0x0410(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          RandomKey_R_B;                                     // 0x0411(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          RandomKey_R_A;                                     // 0x0412(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          RandomKey_G_B;                                     // 0x0413(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          RandomKey_G_A;                                     // 0x0414(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          RandomKey_B_A;                                     // 0x0415(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_416[0x2];                                      // 0x0416(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FUIParticleRange_LinearColorCurve) == 0x000008, "Wrong alignment on FUIParticleRange_LinearColorCurve");
static_assert(sizeof(FUIParticleRange_LinearColorCurve) == 0x000418, "Wrong size on FUIParticleRange_LinearColorCurve");
static_assert(offsetof(FUIParticleRange_LinearColorCurve, Min) == 0x000000, "Member 'FUIParticleRange_LinearColorCurve::Min' has a wrong offset!");
static_assert(offsetof(FUIParticleRange_LinearColorCurve, Max) == 0x000208, "Member 'FUIParticleRange_LinearColorCurve::Max' has a wrong offset!");
static_assert(offsetof(FUIParticleRange_LinearColorCurve, RandomKey_R_G) == 0x000410, "Member 'FUIParticleRange_LinearColorCurve::RandomKey_R_G' has a wrong offset!");
static_assert(offsetof(FUIParticleRange_LinearColorCurve, RandomKey_R_B) == 0x000411, "Member 'FUIParticleRange_LinearColorCurve::RandomKey_R_B' has a wrong offset!");
static_assert(offsetof(FUIParticleRange_LinearColorCurve, RandomKey_R_A) == 0x000412, "Member 'FUIParticleRange_LinearColorCurve::RandomKey_R_A' has a wrong offset!");
static_assert(offsetof(FUIParticleRange_LinearColorCurve, RandomKey_G_B) == 0x000413, "Member 'FUIParticleRange_LinearColorCurve::RandomKey_G_B' has a wrong offset!");
static_assert(offsetof(FUIParticleRange_LinearColorCurve, RandomKey_G_A) == 0x000414, "Member 'FUIParticleRange_LinearColorCurve::RandomKey_G_A' has a wrong offset!");
static_assert(offsetof(FUIParticleRange_LinearColorCurve, RandomKey_B_A) == 0x000415, "Member 'FUIParticleRange_LinearColorCurve::RandomKey_B_A' has a wrong offset!");

// ScriptStruct EasyParticle.EasyParticlePropertyColor
// 0x0660 (0x0660 - 0x0000)
struct FEasyParticlePropertyColor final
{
public:
	EEasyParticlepertyColor_Type                  Type;                                              // 0x0000(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           ColorValue;                                        // 0x0004(0x0010)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FUIParticleRange_Color                 ColorRangeValue;                                   // 0x0014(0x0028)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEasyParticleLinearColorCurve          ColorCurveValue;                                   // 0x0040(0x0208)(Edit, NativeAccessSpecifierPublic)
	struct FUIParticleRange_LinearColorCurve      ColorCurveRangeValue;                              // 0x0248(0x0418)(Edit, NativeAccessSpecifierPublic)
};
static_assert(alignof(FEasyParticlePropertyColor) == 0x000008, "Wrong alignment on FEasyParticlePropertyColor");
static_assert(sizeof(FEasyParticlePropertyColor) == 0x000660, "Wrong size on FEasyParticlePropertyColor");
static_assert(offsetof(FEasyParticlePropertyColor, Type) == 0x000000, "Member 'FEasyParticlePropertyColor::Type' has a wrong offset!");
static_assert(offsetof(FEasyParticlePropertyColor, ColorValue) == 0x000004, "Member 'FEasyParticlePropertyColor::ColorValue' has a wrong offset!");
static_assert(offsetof(FEasyParticlePropertyColor, ColorRangeValue) == 0x000014, "Member 'FEasyParticlePropertyColor::ColorRangeValue' has a wrong offset!");
static_assert(offsetof(FEasyParticlePropertyColor, ColorCurveValue) == 0x000040, "Member 'FEasyParticlePropertyColor::ColorCurveValue' has a wrong offset!");
static_assert(offsetof(FEasyParticlePropertyColor, ColorCurveRangeValue) == 0x000248, "Member 'FEasyParticlePropertyColor::ColorCurveRangeValue' has a wrong offset!");

// ScriptStruct EasyParticle.UIParticleRange_Float
// 0x0008 (0x0008 - 0x0000)
struct FUIParticleRange_Float final
{
public:
	float                                         Min;                                               // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Max;                                               // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FUIParticleRange_Float) == 0x000004, "Wrong alignment on FUIParticleRange_Float");
static_assert(sizeof(FUIParticleRange_Float) == 0x000008, "Wrong size on FUIParticleRange_Float");
static_assert(offsetof(FUIParticleRange_Float, Min) == 0x000000, "Member 'FUIParticleRange_Float::Min' has a wrong offset!");
static_assert(offsetof(FUIParticleRange_Float, Max) == 0x000004, "Member 'FUIParticleRange_Float::Max' has a wrong offset!");

// ScriptStruct EasyParticle.EasyParticleFloatCurve
// 0x0088 (0x0088 - 0x0000)
struct FEasyParticleFloatCurve final
{
public:
	struct FRichCurve                             CurveData;                                         // 0x0000(0x0080)(Edit, NativeAccessSpecifierPublic)
	EUIParticleCurveType                          CurveType;                                         // 0x0080(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Loop;                                              // 0x0081(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_82[0x6];                                       // 0x0082(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(FEasyParticleFloatCurve) == 0x000008, "Wrong alignment on FEasyParticleFloatCurve");
static_assert(sizeof(FEasyParticleFloatCurve) == 0x000088, "Wrong size on FEasyParticleFloatCurve");
static_assert(offsetof(FEasyParticleFloatCurve, CurveData) == 0x000000, "Member 'FEasyParticleFloatCurve::CurveData' has a wrong offset!");
static_assert(offsetof(FEasyParticleFloatCurve, CurveType) == 0x000080, "Member 'FEasyParticleFloatCurve::CurveType' has a wrong offset!");
static_assert(offsetof(FEasyParticleFloatCurve, Loop) == 0x000081, "Member 'FEasyParticleFloatCurve::Loop' has a wrong offset!");

// ScriptStruct EasyParticle.UIParticleRange_FloatCurve
// 0x0110 (0x0110 - 0x0000)
struct FUIParticleRange_FloatCurve final
{
public:
	struct FEasyParticleFloatCurve                Min;                                               // 0x0000(0x0088)(Edit, NativeAccessSpecifierPublic)
	struct FEasyParticleFloatCurve                Max;                                               // 0x0088(0x0088)(Edit, NativeAccessSpecifierPublic)
};
static_assert(alignof(FUIParticleRange_FloatCurve) == 0x000008, "Wrong alignment on FUIParticleRange_FloatCurve");
static_assert(sizeof(FUIParticleRange_FloatCurve) == 0x000110, "Wrong size on FUIParticleRange_FloatCurve");
static_assert(offsetof(FUIParticleRange_FloatCurve, Min) == 0x000000, "Member 'FUIParticleRange_FloatCurve::Min' has a wrong offset!");
static_assert(offsetof(FUIParticleRange_FloatCurve, Max) == 0x000088, "Member 'FUIParticleRange_FloatCurve::Max' has a wrong offset!");

// ScriptStruct EasyParticle.EasyParticlePropertyFloat
// 0x01A8 (0x01A8 - 0x0000)
struct FEasyParticlePropertyFloat final
{
public:
	EEasyParticlepertyFloat_Type                  Type;                                              // 0x0000(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         FloatValue;                                        // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FUIParticleRange_Float                 FloatRangeValue;                                   // 0x0008(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FEasyParticleFloatCurve                FloatCurveValue;                                   // 0x0010(0x0088)(Edit, NativeAccessSpecifierPublic)
	struct FUIParticleRange_FloatCurve            FloatCurveRangeValue;                              // 0x0098(0x0110)(Edit, NativeAccessSpecifierPublic)
};
static_assert(alignof(FEasyParticlePropertyFloat) == 0x000008, "Wrong alignment on FEasyParticlePropertyFloat");
static_assert(sizeof(FEasyParticlePropertyFloat) == 0x0001A8, "Wrong size on FEasyParticlePropertyFloat");
static_assert(offsetof(FEasyParticlePropertyFloat, Type) == 0x000000, "Member 'FEasyParticlePropertyFloat::Type' has a wrong offset!");
static_assert(offsetof(FEasyParticlePropertyFloat, FloatValue) == 0x000004, "Member 'FEasyParticlePropertyFloat::FloatValue' has a wrong offset!");
static_assert(offsetof(FEasyParticlePropertyFloat, FloatRangeValue) == 0x000008, "Member 'FEasyParticlePropertyFloat::FloatRangeValue' has a wrong offset!");
static_assert(offsetof(FEasyParticlePropertyFloat, FloatCurveValue) == 0x000010, "Member 'FEasyParticlePropertyFloat::FloatCurveValue' has a wrong offset!");
static_assert(offsetof(FEasyParticlePropertyFloat, FloatCurveRangeValue) == 0x000098, "Member 'FEasyParticlePropertyFloat::FloatCurveRangeValue' has a wrong offset!");

// ScriptStruct EasyParticle.EasyParticleStateRuntime
// 0x0054 (0x0054 - 0x0000)
struct FEasyParticleStateRuntime final
{
public:
	float                                         Lifetime;                                          // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              Velocity;                                          // 0x0004(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              Position;                                          // 0x000C(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              Size;                                              // 0x0014(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Rotation;                                          // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RotationRate;                                      // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLinearColor                           Color;                                             // 0x0024(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AutoSizeScale;                                     // 0x0034(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              WidgetPositionAbsolute;                            // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector2D                              Pivot;                                             // 0x0040(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ZOrderOffset;                                      // 0x0048(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EEasyParticleDrawEffect                       DrawEffect;                                        // 0x004C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4D[0x3];                                       // 0x004D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         RootEmitterLifetime;                               // 0x0050(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(FEasyParticleStateRuntime) == 0x000004, "Wrong alignment on FEasyParticleStateRuntime");
static_assert(sizeof(FEasyParticleStateRuntime) == 0x000054, "Wrong size on FEasyParticleStateRuntime");
static_assert(offsetof(FEasyParticleStateRuntime, Lifetime) == 0x000000, "Member 'FEasyParticleStateRuntime::Lifetime' has a wrong offset!");
static_assert(offsetof(FEasyParticleStateRuntime, Velocity) == 0x000004, "Member 'FEasyParticleStateRuntime::Velocity' has a wrong offset!");
static_assert(offsetof(FEasyParticleStateRuntime, Position) == 0x00000C, "Member 'FEasyParticleStateRuntime::Position' has a wrong offset!");
static_assert(offsetof(FEasyParticleStateRuntime, Size) == 0x000014, "Member 'FEasyParticleStateRuntime::Size' has a wrong offset!");
static_assert(offsetof(FEasyParticleStateRuntime, Rotation) == 0x00001C, "Member 'FEasyParticleStateRuntime::Rotation' has a wrong offset!");
static_assert(offsetof(FEasyParticleStateRuntime, RotationRate) == 0x000020, "Member 'FEasyParticleStateRuntime::RotationRate' has a wrong offset!");
static_assert(offsetof(FEasyParticleStateRuntime, Color) == 0x000024, "Member 'FEasyParticleStateRuntime::Color' has a wrong offset!");
static_assert(offsetof(FEasyParticleStateRuntime, AutoSizeScale) == 0x000034, "Member 'FEasyParticleStateRuntime::AutoSizeScale' has a wrong offset!");
static_assert(offsetof(FEasyParticleStateRuntime, WidgetPositionAbsolute) == 0x000038, "Member 'FEasyParticleStateRuntime::WidgetPositionAbsolute' has a wrong offset!");
static_assert(offsetof(FEasyParticleStateRuntime, Pivot) == 0x000040, "Member 'FEasyParticleStateRuntime::Pivot' has a wrong offset!");
static_assert(offsetof(FEasyParticleStateRuntime, ZOrderOffset) == 0x000048, "Member 'FEasyParticleStateRuntime::ZOrderOffset' has a wrong offset!");
static_assert(offsetof(FEasyParticleStateRuntime, DrawEffect) == 0x00004C, "Member 'FEasyParticleStateRuntime::DrawEffect' has a wrong offset!");
static_assert(offsetof(FEasyParticleStateRuntime, RootEmitterLifetime) == 0x000050, "Member 'FEasyParticleStateRuntime::RootEmitterLifetime' has a wrong offset!");

}

