#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FieldCommonTerrainRockyPlaceBase

#include "Basic.hpp"

#include "BP_NicolaFieldStaticMeshActorBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FieldCommonTerrainRockyPlaceBase.FieldCommonTerrainRockyPlaceBase_C
// 0x0000 (0x0240 - 0x0240)
class AFieldCommonTerrainRockyPlaceBase_C : public ABP_NicolaFieldStaticMeshActorBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FieldCommonTerrainRockyPlaceBase_C">();
	}
	static class AFieldCommonTerrainRockyPlaceBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFieldCommonTerrainRockyPlaceBase_C>();
	}
};
static_assert(alignof(AFieldCommonTerrainRockyPlaceBase_C) == 0x000008, "Wrong alignment on AFieldCommonTerrainRockyPlaceBase_C");
static_assert(sizeof(AFieldCommonTerrainRockyPlaceBase_C) == 0x000240, "Wrong size on AFieldCommonTerrainRockyPlaceBase_C");

}

