#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ModelDuplicater

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class ModelDuplicater.DpModelBlueprintFunctionLibrary
// 0x0000 (0x0028 - 0x0028)
class UDpModelBlueprintFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static bool ConvertAbsolutePathToVirtualPath(const class FString& InFilename, class FString* OutFilename);
	static bool GetParallelFolderPathFromModelPath(const class FString& ToFilepath, const class FString& FromFilepath, class FString* OutFilename);
	static bool GetProjectFolderNameFromPath(const class FString& InFilepath, class FString* OutProjectName);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"DpModelBlueprintFunctionLibrary">();
	}
	static class UDpModelBlueprintFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDpModelBlueprintFunctionLibrary>();
	}
};
static_assert(alignof(UDpModelBlueprintFunctionLibrary) == 0x000008, "Wrong alignment on UDpModelBlueprintFunctionLibrary");
static_assert(sizeof(UDpModelBlueprintFunctionLibrary) == 0x000028, "Wrong size on UDpModelBlueprintFunctionLibrary");

// Class ModelDuplicater.MyBlueprintFunctionLibrary
// 0x0000 (0x0028 - 0x0028)
class UMyBlueprintFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MyBlueprintFunctionLibrary">();
	}
	static class UMyBlueprintFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMyBlueprintFunctionLibrary>();
	}
};
static_assert(alignof(UMyBlueprintFunctionLibrary) == 0x000008, "Wrong alignment on UMyBlueprintFunctionLibrary");
static_assert(sizeof(UMyBlueprintFunctionLibrary) == 0x000028, "Wrong size on UMyBlueprintFunctionLibrary");

}

