#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NicolaLightingEnvPreset_WeakenLensFlares

#include "Basic.hpp"

#include "BP_NicolaLightingEnvPresetBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NicolaLightingEnvPreset_WeakenLensFlares.NicolaLightingEnvPreset_WeakenLensFlares_C
// 0x0000 (0x0D88 - 0x0D88)
class ANicolaLightingEnvPreset_WeakenLensFlares_C final : public ABP_NicolaLightingEnvPresetBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NicolaLightingEnvPreset_WeakenLensFlares_C">();
	}
	static class ANicolaLightingEnvPreset_WeakenLensFlares_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANicolaLightingEnvPreset_WeakenLensFlares_C>();
	}
};
static_assert(alignof(ANicolaLightingEnvPreset_WeakenLensFlares_C) == 0x000008, "Wrong alignment on ANicolaLightingEnvPreset_WeakenLensFlares_C");
static_assert(sizeof(ANicolaLightingEnvPreset_WeakenLensFlares_C) == 0x000D88, "Wrong size on ANicolaLightingEnvPreset_WeakenLensFlares_C");

}

