#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NicolaLightingEnvPreset_Conifer

#include "Basic.hpp"

#include "BP_NicolaLightingEnvPresetBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NicolaLightingEnvPreset_Conifer.NicolaLightingEnvPreset_Conifer_C
// 0x0000 (0x0D88 - 0x0D88)
class ANicolaLightingEnvPreset_Conifer_C final : public ABP_NicolaLightingEnvPresetBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NicolaLightingEnvPreset_Conifer_C">();
	}
	static class ANicolaLightingEnvPreset_Conifer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANicolaLightingEnvPreset_Conifer_C>();
	}
};
static_assert(alignof(ANicolaLightingEnvPreset_Conifer_C) == 0x000008, "Wrong alignment on ANicolaLightingEnvPreset_Conifer_C");
static_assert(sizeof(ANicolaLightingEnvPreset_Conifer_C) == 0x000D88, "Wrong size on ANicolaLightingEnvPreset_Conifer_C");

}

