#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NicolaLightingEnvPreset_BaramosCastle

#include "Basic.hpp"

#include "BP_NicolaLightingEnvPresetBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NicolaLightingEnvPreset_BaramosCastle.NicolaLightingEnvPreset_BaramosCastle_C
// 0x0000 (0x0D88 - 0x0D88)
class ANicolaLightingEnvPreset_BaramosCastle_C final : public ABP_NicolaLightingEnvPresetBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NicolaLightingEnvPreset_BaramosCastle_C">();
	}
	static class ANicolaLightingEnvPreset_BaramosCastle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANicolaLightingEnvPreset_BaramosCastle_C>();
	}
};
static_assert(alignof(ANicolaLightingEnvPreset_BaramosCastle_C) == 0x000008, "Wrong alignment on ANicolaLightingEnvPreset_BaramosCastle_C");
static_assert(sizeof(ANicolaLightingEnvPreset_BaramosCastle_C) == 0x000D88, "Wrong size on ANicolaLightingEnvPreset_BaramosCastle_C");

}

