#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SL_C02_Romaria_BattleRoad_LevelInstance_1

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SL_C02_Romaria_BattleRoad_LevelInstance_1.SL_C02_Romaria_BattleRoad_C
// 0x0000 (0x0260 - 0x0260)
class ASL_C02_Romaria_BattleRoad_C final : public ANicolaTownDungeonLevel
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SL_C02_Romaria_BattleRoad_C">();
	}
	static class ASL_C02_Romaria_BattleRoad_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASL_C02_Romaria_BattleRoad_C>();
	}
};
static_assert(alignof(ASL_C02_Romaria_BattleRoad_C) == 0x000008, "Wrong alignment on ASL_C02_Romaria_BattleRoad_C");
static_assert(sizeof(ASL_C02_Romaria_BattleRoad_C) == 0x000260, "Wrong size on ASL_C02_Romaria_BattleRoad_C");

}

