#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SL_Room_Lights_L1_LevelInstance_12

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SL_Room_Lights_L1_LevelInstance_12.SL_Room_Lights_L1_C
// 0x0000 (0x0260 - 0x0260)
class ASL_Room_Lights_L1_C final : public ANicolaTownDungeonLevel
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SL_Room_Lights_L1_C">();
	}
	static class ASL_Room_Lights_L1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASL_Room_Lights_L1_C>();
	}
};
static_assert(alignof(ASL_Room_Lights_L1_C) == 0x000008, "Wrong alignment on ASL_Room_Lights_L1_C");
static_assert(sizeof(ASL_Room_Lights_L1_C) == 0x000260, "Wrong size on ASL_Room_Lights_L1_C");

}

