#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SL_Underground_Lights_LevelInstance_27

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SL_Underground_Lights_LevelInstance_27.SL_Underground_Lights_C
// 0x0000 (0x0260 - 0x0260)
class SL_Underground_Lights_LevelInstance_27::ASL_Underground_Lights_C final : public ANicolaTownDungeonLevel
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BlueprintGeneratedClass SL_Underground_Lights_LevelInstance_27.SL_Underground_Lights_C", true, "SL_Underground_Lights_C">();
	}
	static class SL_Underground_Lights_LevelInstance_27::ASL_Underground_Lights_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<SL_Underground_Lights_LevelInstance_27::ASL_Underground_Lights_C>();
	}
};
static_assert(alignof(SL_Underground_Lights_LevelInstance_27::ASL_Underground_Lights_C) == 0x000008, "Wrong alignment on SL_Underground_Lights_LevelInstance_27::ASL_Underground_Lights_C");
static_assert(sizeof(SL_Underground_Lights_LevelInstance_27::ASL_Underground_Lights_C) == 0x000260, "Wrong size on SL_Underground_Lights_LevelInstance_27::ASL_Underground_Lights_C");

}

