#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_Battle_PlayerDamage2

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_Battle_PlayerDamage2.WB_Battle_PlayerDamage2_C
// 0x0010 (0x03C0 - 0x03B0)
class UWB_Battle_PlayerDamage2_C final : public UCommonWindowWidget
{
public:
	class UWB_Battle_PlayerDamage2_Item_00_C*     Zero0;                                             // 0x03B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_Battle_PlayerDamage2_Item_00_LOC_C* Zero1;                                             // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_Battle_PlayerDamage2_C">();
	}
	static class UWB_Battle_PlayerDamage2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_Battle_PlayerDamage2_C>();
	}
};
static_assert(alignof(UWB_Battle_PlayerDamage2_C) == 0x000008, "Wrong alignment on UWB_Battle_PlayerDamage2_C");
static_assert(sizeof(UWB_Battle_PlayerDamage2_C) == 0x0003C0, "Wrong size on UWB_Battle_PlayerDamage2_C");
static_assert(offsetof(UWB_Battle_PlayerDamage2_C, Zero0) == 0x0003B0, "Member 'UWB_Battle_PlayerDamage2_C::Zero0' has a wrong offset!");
static_assert(offsetof(UWB_Battle_PlayerDamage2_C, Zero1) == 0x0003B8, "Member 'UWB_Battle_PlayerDamage2_C::Zero1' has a wrong offset!");

}

