#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_Common_NoItemText

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_Common_NoItemText.WB_Common_NoItemText_C
// 0x0000 (0x0328 - 0x0328)
class UWB_Common_NoItemText_C final : public UCommonItemWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_Common_NoItemText_C">();
	}
	static class UWB_Common_NoItemText_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_Common_NoItemText_C>();
	}
};
static_assert(alignof(UWB_Common_NoItemText_C) == 0x000008, "Wrong alignment on UWB_Common_NoItemText_C");
static_assert(sizeof(UWB_Common_NoItemText_C) == 0x000328, "Wrong size on UWB_Common_NoItemText_C");

}

