#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_Field_NextGuide_Window1

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_Field_NextGuide_Window1.WB_Field_NextGuide_Window1_C
// 0x0010 (0x03C0 - 0x03B0)
class UWB_Field_NextGuide_Window1_C final : public UCommonWindowWidget
{
public:
	class UWB_Field_NextGuide_List1_C*            ItemList;                                          // 0x03B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TitleBG;                                           // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_Field_NextGuide_Window1_C">();
	}
	static class UWB_Field_NextGuide_Window1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_Field_NextGuide_Window1_C>();
	}
};
static_assert(alignof(UWB_Field_NextGuide_Window1_C) == 0x000008, "Wrong alignment on UWB_Field_NextGuide_Window1_C");
static_assert(sizeof(UWB_Field_NextGuide_Window1_C) == 0x0003C0, "Wrong size on UWB_Field_NextGuide_Window1_C");
static_assert(offsetof(UWB_Field_NextGuide_Window1_C, ItemList) == 0x0003B0, "Member 'UWB_Field_NextGuide_Window1_C::ItemList' has a wrong offset!");
static_assert(offsetof(UWB_Field_NextGuide_Window1_C, TitleBG) == 0x0003B8, "Member 'UWB_Field_NextGuide_Window1_C::TitleBG' has a wrong offset!");

}

