#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_Flipbook

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_Flipbook.WB_Flipbook_C
// 0x0008 (0x0400 - 0x03F8)
class UWB_Flipbook_C final : public UFlipbookWidget
{
public:
	int32                                         FramesTotalOrig;                                   // 0x03F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_Flipbook_C">();
	}
	static class UWB_Flipbook_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_Flipbook_C>();
	}
};
static_assert(alignof(UWB_Flipbook_C) == 0x000008, "Wrong alignment on UWB_Flipbook_C");
static_assert(sizeof(UWB_Flipbook_C) == 0x000400, "Wrong size on UWB_Flipbook_C");
static_assert(offsetof(UWB_Flipbook_C, FramesTotalOrig) == 0x0003F8, "Member 'UWB_Flipbook_C::FramesTotalOrig' has a wrong offset!");

}

