#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_FieldButtonGuide_EventSkip

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_FieldButtonGuide_EventSkip.WB_FieldButtonGuide_EventSkip_C
// 0x0008 (0x03C8 - 0x03C0)
class UWB_FieldButtonGuide_EventSkip_C final : public UCommonRootWidget
{
public:
	class UWB_FieldButtonGuide_EventSkip_Item_C*  EventSkip;                                         // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_FieldButtonGuide_EventSkip_C">();
	}
	static class UWB_FieldButtonGuide_EventSkip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_FieldButtonGuide_EventSkip_C>();
	}
};
static_assert(alignof(UWB_FieldButtonGuide_EventSkip_C) == 0x000008, "Wrong alignment on UWB_FieldButtonGuide_EventSkip_C");
static_assert(sizeof(UWB_FieldButtonGuide_EventSkip_C) == 0x0003C8, "Wrong size on UWB_FieldButtonGuide_EventSkip_C");
static_assert(offsetof(UWB_FieldButtonGuide_EventSkip_C, EventSkip) == 0x0003C0, "Member 'UWB_FieldButtonGuide_EventSkip_C::EventSkip' has a wrong offset!");

}

