#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_MessageWindowXR_Root

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_MessageWindowXR_Root.WB_MessageWindowXR_Root_C
// 0x0010 (0x03D0 - 0x03C0)
class UWB_MessageWindowXR_Root_C final : public UCommonRootWidget
{
public:
	class UNicolaRichTextBlock*                   WidthCheckText;                                    // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_Message_Window_C*                   WindowMessageCenter;                               // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_MessageWindowXR_Root_C">();
	}
	static class UWB_MessageWindowXR_Root_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_MessageWindowXR_Root_C>();
	}
};
static_assert(alignof(UWB_MessageWindowXR_Root_C) == 0x000008, "Wrong alignment on UWB_MessageWindowXR_Root_C");
static_assert(sizeof(UWB_MessageWindowXR_Root_C) == 0x0003D0, "Wrong size on UWB_MessageWindowXR_Root_C");
static_assert(offsetof(UWB_MessageWindowXR_Root_C, WidthCheckText) == 0x0003C0, "Member 'UWB_MessageWindowXR_Root_C::WidthCheckText' has a wrong offset!");
static_assert(offsetof(UWB_MessageWindowXR_Root_C, WindowMessageCenter) == 0x0003C8, "Member 'UWB_MessageWindowXR_Root_C::WindowMessageCenter' has a wrong offset!");

}

