#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_MBREncount_Encount_Window

#include "Basic.hpp"

#include "WB_MBREncount_Encount_Window_classes.hpp"
#include "WB_MBREncount_Encount_Window_parameters.hpp"


namespace SDK
{

// Function WB_MBREncount_Encount_Window.WB_MBREncount_Encount_Window_C.SequenceEvent__ENTRYPOINTWB_MBREncount_Encount_Window_0
// (Public, BlueprintCallable, BlueprintEvent)

void UWB_MBREncount_Encount_Window_C::SequenceEvent__ENTRYPOINTWB_MBREncount_Encount_Window_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_MBREncount_Encount_Window_C", "SequenceEvent__ENTRYPOINTWB_MBREncount_Encount_Window_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_MBREncount_Encount_Window.WB_MBREncount_Encount_Window_C.MBREncount_WhiteOut
// (BlueprintCallable, BlueprintEvent)

void UWB_MBREncount_Encount_Window_C::MBREncount_WhiteOut()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_MBREncount_Encount_Window_C", "MBREncount_WhiteOut");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_MBREncount_Encount_Window.WB_MBREncount_Encount_Window_C.ExecuteUbergraph_WB_MBREncount_Encount_Window
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_MBREncount_Encount_Window_C::ExecuteUbergraph_WB_MBREncount_Encount_Window(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_MBREncount_Encount_Window_C", "ExecuteUbergraph_WB_MBREncount_Encount_Window");

	Params::WB_MBREncount_Encount_Window_C_ExecuteUbergraph_WB_MBREncount_Encount_Window Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

