#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_MiniMapMenu_WindowDrawMap

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_MiniMapMenu_WindowDrawMap.WB_MiniMapMenu_WindowDrawMap_C
// 0x0010 (0x03C8 - 0x03B8)
class UWB_MiniMapMenu_WindowDrawMap_C final : public UCommonMiniMapWidget
{
public:
	class UImage*                                 ImageMap;                                          // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 MaterialMapAppend;                                 // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_MiniMapMenu_WindowDrawMap_C">();
	}
	static class UWB_MiniMapMenu_WindowDrawMap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_MiniMapMenu_WindowDrawMap_C>();
	}
};
static_assert(alignof(UWB_MiniMapMenu_WindowDrawMap_C) == 0x000008, "Wrong alignment on UWB_MiniMapMenu_WindowDrawMap_C");
static_assert(sizeof(UWB_MiniMapMenu_WindowDrawMap_C) == 0x0003C8, "Wrong size on UWB_MiniMapMenu_WindowDrawMap_C");
static_assert(offsetof(UWB_MiniMapMenu_WindowDrawMap_C, ImageMap) == 0x0003B8, "Member 'UWB_MiniMapMenu_WindowDrawMap_C::ImageMap' has a wrong offset!");
static_assert(offsetof(UWB_MiniMapMenu_WindowDrawMap_C, MaterialMapAppend) == 0x0003C0, "Member 'UWB_MiniMapMenu_WindowDrawMap_C::MaterialMapAppend' has a wrong offset!");

}

