#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_MBREncount_Root

#include "Basic.hpp"

#include "Nicola_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WB_MBREncount_Root.WB_MBREncount_Root_C
// 0x0010 (0x03D0 - 0x03C0)
class UWB_MBREncount_Root_C final : public UCommonRootWidget
{
public:
	class UWB_MBREncount_Encount_Window_C*        Encount;                                           // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWB_MBREncount_Encount_WindowItem_C*    Render;                                            // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WB_MBREncount_Root_C">();
	}
	static class UWB_MBREncount_Root_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWB_MBREncount_Root_C>();
	}
};
static_assert(alignof(UWB_MBREncount_Root_C) == 0x000008, "Wrong alignment on UWB_MBREncount_Root_C");
static_assert(sizeof(UWB_MBREncount_Root_C) == 0x0003D0, "Wrong size on UWB_MBREncount_Root_C");
static_assert(offsetof(UWB_MBREncount_Root_C, Encount) == 0x0003C0, "Member 'UWB_MBREncount_Root_C::Encount' has a wrong offset!");
static_assert(offsetof(UWB_MBREncount_Root_C, Render) == 0x0003C8, "Member 'UWB_MBREncount_Root_C::Render' has a wrong offset!");

}

